services:
  db:
    container_name: softweb
    image: postgres:latest
    environment:
      POSTGRES_USER: yogiP05
      POSTGRES_PASSWORD: password
      POSTGRES_DB: softweb
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
